// Code generated by protoc-gen-go.
// source: src/github.com/henrikssn/stored/overlay/msg.proto
// DO NOT EDIT!

/*
Package overlay is a generated protocol buffer package.

It is generated from these files:
	src/github.com/henrikssn/stored/overlay/msg.proto

It has these top-level messages:
	Msg
	JoinRequest
	JoinResponse
	HeartbeatRequest
	HeartbeatResponse
	LeaveRequest
	LeaveResponse
	Member
	NetworkInfo
	GetRequest
	GetResponse
	PutRequest
	PutResponse
*/
package overlay

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Msg_Cmd int32

const (
	Msg_NOP              Msg_Cmd = 0
	Msg_JOIN             Msg_Cmd = 1
	Msg_COORDINATOR_INFO Msg_Cmd = 2
	Msg_NETWORK_INFO     Msg_Cmd = 3
	Msg_HEARTBEAT        Msg_Cmd = 4
	Msg_LEAVE            Msg_Cmd = 5
	Msg_GET              Msg_Cmd = 6
	Msg_PUT              Msg_Cmd = 7
)

var Msg_Cmd_name = map[int32]string{
	0: "NOP",
	1: "JOIN",
	2: "COORDINATOR_INFO",
	3: "NETWORK_INFO",
	4: "HEARTBEAT",
	5: "LEAVE",
	6: "GET",
	7: "PUT",
}
var Msg_Cmd_value = map[string]int32{
	"NOP":              0,
	"JOIN":             1,
	"COORDINATOR_INFO": 2,
	"NETWORK_INFO":     3,
	"HEARTBEAT":        4,
	"LEAVE":            5,
	"GET":              6,
	"PUT":              7,
}

func (x Msg_Cmd) Enum() *Msg_Cmd {
	p := new(Msg_Cmd)
	*p = x
	return p
}
func (x Msg_Cmd) String() string {
	return proto.EnumName(Msg_Cmd_name, int32(x))
}
func (x *Msg_Cmd) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Msg_Cmd_value, data, "Msg_Cmd")
	if err != nil {
		return err
	}
	*x = Msg_Cmd(value)
	return nil
}

type Msg_Type int32

const (
	Msg_UNEXPECTED Msg_Type = 0
	Msg_REQUEST    Msg_Type = 1
	Msg_RESPONSE   Msg_Type = 2
	Msg_INFO       Msg_Type = 3
)

var Msg_Type_name = map[int32]string{
	0: "UNEXPECTED",
	1: "REQUEST",
	2: "RESPONSE",
	3: "INFO",
}
var Msg_Type_value = map[string]int32{
	"UNEXPECTED": 0,
	"REQUEST":    1,
	"RESPONSE":   2,
	"INFO":       3,
}

func (x Msg_Type) Enum() *Msg_Type {
	p := new(Msg_Type)
	*p = x
	return p
}
func (x Msg_Type) String() string {
	return proto.EnumName(Msg_Type_name, int32(x))
}
func (x *Msg_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Msg_Type_value, data, "Msg_Type")
	if err != nil {
		return err
	}
	*x = Msg_Type(value)
	return nil
}

type JoinResponse_Status int32

const (
	JoinResponse_UNEXPECTED_ERROR JoinResponse_Status = 0
	JoinResponse_OK               JoinResponse_Status = 1
	JoinResponse_NOT_COORDINATOR  JoinResponse_Status = 2
)

var JoinResponse_Status_name = map[int32]string{
	0: "UNEXPECTED_ERROR",
	1: "OK",
	2: "NOT_COORDINATOR",
}
var JoinResponse_Status_value = map[string]int32{
	"UNEXPECTED_ERROR": 0,
	"OK":               1,
	"NOT_COORDINATOR":  2,
}

func (x JoinResponse_Status) Enum() *JoinResponse_Status {
	p := new(JoinResponse_Status)
	*p = x
	return p
}
func (x JoinResponse_Status) String() string {
	return proto.EnumName(JoinResponse_Status_name, int32(x))
}
func (x *JoinResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(JoinResponse_Status_value, data, "JoinResponse_Status")
	if err != nil {
		return err
	}
	*x = JoinResponse_Status(value)
	return nil
}

type GetResponse_Status int32

const (
	GetResponse_UNEXPECTED GetResponse_Status = 0
	GetResponse_OK         GetResponse_Status = 1
	GetResponse_NOT_FOUND  GetResponse_Status = 2
)

var GetResponse_Status_name = map[int32]string{
	0: "UNEXPECTED",
	1: "OK",
	2: "NOT_FOUND",
}
var GetResponse_Status_value = map[string]int32{
	"UNEXPECTED": 0,
	"OK":         1,
	"NOT_FOUND":  2,
}

func (x GetResponse_Status) Enum() *GetResponse_Status {
	p := new(GetResponse_Status)
	*p = x
	return p
}
func (x GetResponse_Status) String() string {
	return proto.EnumName(GetResponse_Status_name, int32(x))
}
func (x *GetResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetResponse_Status_value, data, "GetResponse_Status")
	if err != nil {
		return err
	}
	*x = GetResponse_Status(value)
	return nil
}

type PutResponse_Status int32

const (
	PutResponse_UNEXPECTED PutResponse_Status = 0
	PutResponse_OK         PutResponse_Status = 1
	PutResponse_NOT_FOUND  PutResponse_Status = 2
)

var PutResponse_Status_name = map[int32]string{
	0: "UNEXPECTED",
	1: "OK",
	2: "NOT_FOUND",
}
var PutResponse_Status_value = map[string]int32{
	"UNEXPECTED": 0,
	"OK":         1,
	"NOT_FOUND":  2,
}

func (x PutResponse_Status) Enum() *PutResponse_Status {
	p := new(PutResponse_Status)
	*p = x
	return p
}
func (x PutResponse_Status) String() string {
	return proto.EnumName(PutResponse_Status_name, int32(x))
}
func (x *PutResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PutResponse_Status_value, data, "PutResponse_Status")
	if err != nil {
		return err
	}
	*x = PutResponse_Status(value)
	return nil
}

type Msg struct {
	Cmd              *Msg_Cmd  `protobuf:"varint,1,opt,name=cmd,enum=overlay.Msg_Cmd" json:"cmd,omitempty"`
	Type             *Msg_Type `protobuf:"varint,2,opt,name=type,enum=overlay.Msg_Type" json:"type,omitempty"`
	Seqn             *int64    `protobuf:"varint,3,opt,name=seqn" json:"seqn,omitempty"`
	Data             []byte    `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}

func (m *Msg) GetCmd() Msg_Cmd {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return Msg_NOP
}

func (m *Msg) GetType() Msg_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Msg_UNEXPECTED
}

func (m *Msg) GetSeqn() int64 {
	if m != nil && m.Seqn != nil {
		return *m.Seqn
	}
	return 0
}

func (m *Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type JoinRequest struct {
	Addr             *string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}

func (m *JoinRequest) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

type JoinResponse struct {
	Status           *JoinResponse_Status `protobuf:"varint,1,opt,name=status,enum=overlay.JoinResponse_Status" json:"status,omitempty"`
	Coordinator      *Member              `protobuf:"bytes,2,opt,name=coordinator" json:"coordinator,omitempty"`
	YourId           *int64               `protobuf:"varint,3,opt,name=your_id" json:"your_id,omitempty"`
	Members          []*Member            `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}

func (m *JoinResponse) GetStatus() JoinResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return JoinResponse_UNEXPECTED_ERROR
}

func (m *JoinResponse) GetCoordinator() *Member {
	if m != nil {
		return m.Coordinator
	}
	return nil
}

func (m *JoinResponse) GetYourId() int64 {
	if m != nil && m.YourId != nil {
		return *m.YourId
	}
	return 0
}

func (m *JoinResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type HeartbeatRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}

type HeartbeatResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}

type LeaveRequest struct {
	KickedMember     *Member   `protobuf:"bytes,1,opt,name=kicked_member" json:"kicked_member,omitempty"`
	Members          []*Member `protobuf:"bytes,2,rep,name=members" json:"members,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *LeaveRequest) Reset()         { *m = LeaveRequest{} }
func (m *LeaveRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveRequest) ProtoMessage()    {}

func (m *LeaveRequest) GetKickedMember() *Member {
	if m != nil {
		return m.KickedMember
	}
	return nil
}

func (m *LeaveRequest) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type LeaveResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LeaveResponse) Reset()         { *m = LeaveResponse{} }
func (m *LeaveResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveResponse) ProtoMessage()    {}

type Member struct {
	UdpAddr          *string   `protobuf:"bytes,1,opt,name=udp_addr" json:"udp_addr,omitempty"`
	Id               *int64    `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Replicas         []*Member `protobuf:"bytes,3,rep,name=replicas" json:"replicas,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}

func (m *Member) GetUdpAddr() string {
	if m != nil && m.UdpAddr != nil {
		return *m.UdpAddr
	}
	return ""
}

func (m *Member) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Member) GetReplicas() []*Member {
	if m != nil {
		return m.Replicas
	}
	return nil
}

type NetworkInfo struct {
	Coordinator      *Member   `protobuf:"bytes,1,opt,name=coordinator" json:"coordinator,omitempty"`
	Members          []*Member `protobuf:"bytes,2,rep,name=members" json:"members,omitempty"`
	HashToId         []int64   `protobuf:"varint,3,rep,name=hash_to_id" json:"hash_to_id,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *NetworkInfo) Reset()         { *m = NetworkInfo{} }
func (m *NetworkInfo) String() string { return proto.CompactTextString(m) }
func (*NetworkInfo) ProtoMessage()    {}

func (m *NetworkInfo) GetCoordinator() *Member {
	if m != nil {
		return m.Coordinator
	}
	return nil
}

func (m *NetworkInfo) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *NetworkInfo) GetHashToId() []int64 {
	if m != nil {
		return m.HashToId
	}
	return nil
}

type GetRequest struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	SubKey           *string `protobuf:"bytes,2,opt,name=sub_key" json:"sub_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}

func (m *GetRequest) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *GetRequest) GetSubKey() string {
	if m != nil && m.SubKey != nil {
		return *m.SubKey
	}
	return ""
}

type GetResponse struct {
	Status           *GetResponse_Status `protobuf:"varint,1,opt,name=status,enum=overlay.GetResponse_Status" json:"status,omitempty"`
	Value            []byte              `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}

func (m *GetResponse) GetStatus() GetResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GetResponse_UNEXPECTED
}

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutRequest struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	SubKey           *string `protobuf:"bytes,2,opt,name=sub_key" json:"sub_key,omitempty"`
	Value            []byte  `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}

func (m *PutRequest) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *PutRequest) GetSubKey() string {
	if m != nil && m.SubKey != nil {
		return *m.SubKey
	}
	return ""
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutResponse struct {
	Status           *PutResponse_Status `protobuf:"varint,1,opt,name=status,enum=overlay.PutResponse_Status" json:"status,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}

func (m *PutResponse) GetStatus() PutResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return PutResponse_UNEXPECTED
}

func init() {
	proto.RegisterEnum("overlay.Msg_Cmd", Msg_Cmd_name, Msg_Cmd_value)
	proto.RegisterEnum("overlay.Msg_Type", Msg_Type_name, Msg_Type_value)
	proto.RegisterEnum("overlay.JoinResponse_Status", JoinResponse_Status_name, JoinResponse_Status_value)
	proto.RegisterEnum("overlay.GetResponse_Status", GetResponse_Status_name, GetResponse_Status_value)
	proto.RegisterEnum("overlay.PutResponse_Status", PutResponse_Status_name, PutResponse_Status_value)
}
